name: "Documentation check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "package.json, Manual_Files.md, Manual_Files_es.md, Manual_Files_pr.md, README.md, README.es.md, README.pr.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the documentation exists
        run: echo All documentation exists!